### ISSUE TITLE
Integrate into Apache Commons Configuration

### ISSUE THREAD

**Issue by e1528532** [ElektraInitiative/libelektra#1085]
I will integrate libelektra into the apache commons configuration library, so elektra can be easily used in java applications without having to use the rather low level jna bindings. Furthermore, this allows to use elektra in spring applications, as commons configurations will also make the gap between them.

# TODOs

- [ ] Research on how to extend the apache commons configuration library with elektra backend
- [ ] Implement a simple version of the integration
- [ ] Implement an advanced version of the integration where we can use hierarchial keys and things like that
- [ ] Provide tests to cover the integration
- [ ] Release the integration (Maybe via maven again, so that its easy to use?)

**Comment by markus2330** [comment]
Thanks for creating the issue!

I think the other way round would be also interesting: Having a jni plugin that uses Apache Commons Configuration to write out configuration files. We could use this plugin as benchmark to our own plugins.
