### ISSUE TITLE
project diary

### ISSUE THREAD

**Issue by e1528532** [ElektraInitiative/libelektra#1087]
This is an overview of my elektra tasks to keep track of my current progress and my goals for the next months.
# Tasks & Estimation
- [X] #1084 Beginner Issues & Tutorial improvements, #1090 ini improvements on duplicate message
    Currently ~20h
    Estimated ~20h
- [ ] #1176 rate tutorials #1311 tutorial improvements
    Currenlty 4h30
    Estimated ~10h
- [ ] #280 Create Getting Started Tutorials
    Currently 0h
    Estimated ~10-30h (depending on how much tutorials)
- [X] #1083 Installing JNA bindings
    Currently ~9h
    Estimated ~10h
- [X] #1278 #1277 JNI documentation
    Currently ~4
    Estimated ~4 (we don't want to spend more time on it)
- [X] #1510 #1514  fix getopt
    Currently 2h30
- [X] #1086 JNA binding improvements #1353  #1360 
    Currently ~44h15
    Estimated ~20h
- [X] #1545 strict prototypes
    Currently 2h30
- [X] #1132 global umount
    Currently 4h
    Estimated ~7h
- [ ] #1012 config file examples
    Currently 0h
    Estimated ~4h
- [x] #1047 implement file plugin done by thomas
    Currently 0h
    Estimated ~8h
- [X] #1167 #1296 #1310 kdb complete #1336  #1328 
    Currently ~41h30
    Estimated ~24h
- [X] #1345 kdb ls depth
    Currently 4h (mostly shellrecorder...)
- [X] #1328 fix basename deletion bug & tests
    Currently 3h
- [X] #1002 relative key
  Currently 3h
- [ ] #1248 complexity analysis pmccabe
    Currently ~0h15
    Estimated ~8h (depending on how much methods we fix and if we want to add tests, this can vary)
- [X] #788  fix sanitizer issues #1558 
    Currently 13h30
    Estimated ~10h (maybe more or less, depends on how hard the issues are to fix)
- [X] #1286 #1295 #1326 reformat sources / script commons on macOS
    Currently ~5h
    Estimated ~3h
- [X] Script refactoring and fixes (bashisms #1352  #1361  #1256)
   Currently ~ 6h30
- [ ] #1033 proof read docu
   Currently 0h30
   Estimated ~2-3h
- [ ] #1370 cbmc
  Currently 3h
- [X] General Stuff (meetings, code reviews, planning, git, etc.)
   Currently ~32h30
   Estimated ~30h
- [X] #1362 static code checkers
   Currently 21h30
- [X] XML Xerces #1280 #1454 #1451 #1400 
  Currently 55h45
  Estimated 60
- [X] fix kdb get bug 
  Currently 1h
- [X] Randoop & jna improvements #1530 
  Currently 16h15
- [X] User Study Puppet & Elektra
  Currently 4h
## Current time tracking
Currently: 302:00/300:00

# Weekly Timelines (Calendar weeks, some weeks in advance, long term goals see milestones)
CW 51: Tutorials, JNA Bindings ~ 10h (holidays)
CW 52: Tutorials, JNA Bindings ~ 10h (holidays)
CW 1: Tutorials, Finish JNA Binding improvements, documentation improvements ~ 10h (exam)
CW 2: JNI plugin ~ 10h (exam)
CW 3: kdb complete ~ 15h
CW 4: kdb complete, common scripts ~ 15h
CW 5: kdb complete, maven~25h
CW 6: kdb complete, maven, various smaller issues ~25h
CW 7: kdb complete, maven, script improvements
CW 8: kdb complete, maven, fix bashisms
CW 9: maven, fix asan issue? pmcmccabe?
CW 10: file plugin, global umount tool

# Milestones
M1 - 31.1.2017 - ~100h - Tutorials & JNA Bindings  & First Plugin/Tool Development
M2 - 28.2.2017 - ~200h - More plugin development (complete, file) and tools (kdb unmount), some fixing (adress sanitizing, complex methods)
M3 - 31.3.2017 - ~300h - Unify type System, GZip Plugin, other fixes and improvements, probably not haskell

**Comment by markus2330** [comment]
Hi, please update to have:

- estimated working times, so that we can rearrange with priority
- concrete timelines (ideally every week!) until a final timeline (more precise for next week, and only on goal level for other milestones, final timeline)

**Comment by markus2330** [comment]
Please update which parts are in the first milestone from Tasks & Estimation. And please remove "Apache Commons Integration" and instead do more of the already existing  issues. E.g. #1012 would be really nice to have.

**Comment by markus2330** [comment]
@tom-wa You might want to take a look here.
