### ISSUE TITLE
openicc validation

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1137]
Openicc seems now to be used in practise. Unfortunately it is not valided yet, i.e. users can destroy it structure, write unwanted values, or even generate invalid json (if arrays and objects are mixed up).

Of course we do not want that do happen, thus we should provide a nice spec file that provides full validation.

The current largest file we have is src/plugins/yajl/yajl/OpenICC_device_config_DB.json and of course there is the [openicc specification](http://www.openicc.info/index.php?title=OpenICC_Configuration_0.1).

For me it looks like (@beku, please correct me if I am wrong):

- [x] /org/freedesktop/openicc/device/camera/#/EXIF_manufacturer, EXIF_mnft, EXIF_model are strings with any content?
 - [x] EXIF_serial is some int? No bounds?
 - [ ] automatic_assigment: boolean represented with 0 or 1?
 - [ ] creation_date, expire_date would be a job for  #1096
 - [ ] icc_profile seems like a file name but where is it located in the file system? Should we check if it is present?
 - [ ] prefix seems like a constrainted string? Only uppercase and _? Could be done with a simple regex.
- [ ] in  /org/freedesktop/openicc/device/monitor/#/EDID_blue_x and EDID_blue_y, and so on, floats?
- [ ] EDID_date seems like a special date? Maybe also a job for #1096
- [ ] EDID_model_id, looks like it needs some range specification #524
- [ ] array checks #1862

@beku: What do you think, what should we check for?

**Comment by markus2330** [comment]
And are there required fields?
Are completely unmentioned keys okay? (e.g. except or reject  `/org/freedesktop/openicc/device/monitor/#/EDID_blah_x`)
Can there be other categories next to camera and monitor?
Are there constraints between the values?
Should we even check against some names that some Xserver API gives us (we would help here though how to use the Xserver APIs)?

**Comment by beku** [comment]
I'd like to submit the validation description/code. 

Form validation is typical performed in a UI. However especially the device keys are not always freely editable. Monitor values could by checked by the belonging EDID, which needs to be parsed by a EDID parser using libXcm. In Oyranos/git the EDID itself is included hex encoded as key "EDID", which would allow for a concise check. But Oyranos does not yet use it for consistency checks.

Your idea sounds to me like xslt (https://www.w3.org/TR/xslt-30/#json). A formal description which values are in range might be a light weight direction. Do you have something in mind in which format we (OpenICC) can describe valid settings?

On the procedural side:
Oyranos has a XForms subset XML format, which describes settings(keys) and the according possible values including a additional description of the keys and values. These XML forms are generated at runtime in order to cover system state specific things like list of installed ICC profiles, list of installed profiles matching a devices, list of online profiles matching a device etc. For such processing a interface would be needed, which asks an in elektra registered module for alternative values.
The API in Oyranos is here -  https://codedocs.xyz/oyranos-cms/oyranos/group__options.html#gaec95a1ed7588fdac09fd51b34eb2597c  (The widget enum corresponds to elektra keys.)

**Comment by markus2330** [comment]
> I'd like to submit the validation description/code.

Thanks! @tom-wa will also work on it. Ideally, @tom-wa would write plugins that are generally useful for everyone and you help with very specific plugins such as EDID validation.

> Form validation is typical performed in a UI.

Yes, it is but it should not happen exclusively there. If it is also done within the database, you also cover every other way data could be manipulated such as the `kdb` tools, qt-gui, or soon the web ui.

> Your idea sounds to me like xslt (https://www.w3.org/TR/xslt-30/#json). A formal description which values are in range might be a light weight direction.

Yes, it is similar, but Elektra is much more powerful because you can extend validation by further plugins. See https://github.com/ElektraInitiative/libelektra/blob/master/src/plugins/README.md#checker for what we currently have.

> Do you have something in mind in which format we (OpenICC) can describe valid settings?

Thus the specification also lives within Elektra, you can choose the syntax. Unfortunately, not every storage plugin allows meta-data which is necessary to specify validation. At the moment ini is the best choice. The values you use for the specifications are defined in http://tree.libelektra.org/doc/METADATA.ini. The validation itself is implemented in the plugins: They take the metadata and check if the value is like it should be. For examples look into the different checker plugins e.g. http://tree.libelektra.org/src/plugins/enum. There are also tutorials: http://tree.libelektra.org/doc/tutorials/mount.md (section meta data) and http://tree.libelektra.org/doc/tutorials/validation.md.

> Oyranos has a XForms subset XML format, ... are generated at runtime

I would go for the obvious validations first, can you generate the file for the non-dynamic parts (in particular OpenICC parts?)? For the other parts we likely need to implement new plugins which might even need to communicate with oyranos?

**Comment by beku** [comment]
Spec tester 0.1
---------------------

The purpose is to demonstrate, on how to write specs with plain text editors, which are human readable and presentable. Additionally this spec needs to be machine readable, transformable and verifiable. 

The text is enclosed in \`\`\`yaml spec text \`\`\` for better rendering on github and easier extraction after being committed.

```yaml
comment: This is a specification for OpenICC DB. It shall comply as close as possible to the ICC specification. Further are some properties specified, which are common case and widely used. Those may be outside of ICC.
org/freedesktop/openicc/behaviour/rendering_intent:
    type: integer
    min: 0
    max: 3
    step: 1
    default: 0
    name: Rendering Intent
    description: Rendering intent for color space transformations.
    help: Rendering intent for color space transformations is typically the Relative Colorimetric intent plus Black Point Compensation or the Perceptual intent.
    values:
      0:
        name: Perceptual
        description: Photographic, pleasing, ICC Profile defined color transform
        help: This transform is defined by the ICC profile generating vendor.
          It shall preserve the overall tonal appearance of a image.
      1:
        name: Relative Colorimetric
        description: Color accurate with white point adapted to D50
        help: This intent is the same like Absolute Colorimetric, but has it's white point adapted to D50 using Bradford chromatic adaption.
      2:
       name: Saturation
       description: Colorful graphics
       help: This transform is defined by the ICC profile generating vendor.
         It shall show clear, saturated colors taking device specifics into account.
      3:
        name: Absolutee Colorimetric
        description: Color accurate rendering
        help: This intent is the same like Relative Colorimetric, but has it's white point not adapted. The profiles media white point is taken into account.
    ref: Specification ICC.1:2010-12
    ref.url: http://www.color.org/icc_specs2.xalter

org/freedesktop/openicc/behaviour/rendering_bpc:
    type: boolean
    default: 0
    name: Use Black Point Compensation
    description: BPC affects often only the Relative Colorimetric Rendering intent.
    help: BPC affects often only the Relative Colorimetric Rendering intent.
    values:
       0:
         name: "No"
       1:
         name: "Yes"
```

The above yaml should be c&p able into https://www.json2yaml.com/ for conversion to JSON.

**Comment by markus2330** [comment]
Thank you for your input!

Elektra's specification looks nearly identical to what you propose, only the "values" would be an "enum".

> The above yaml should be c&p able ...

No online service is needed, Elektra can also convert between YAML and JSON:

```
# Given your content above is stored as /usr/share/elektra/specification/openicc.spec
kdb mount openicc.spec spec/openicc yaml
kdb export spec/openicc yajl
```

**Comment by markus2330** [comment]
@beku do you want to write such a specification? We could provide help in how to do it. @Piankero recently wrote two larger specifications.
