### ISSUE TITLE
Provide More High-Level APIs

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1270]
Provide High-Level APIs (in additional libraries) such as:

- [ ] C++ typed api by checking metadata see #1092
- [ ] directly get/set values in C standard types, see [decisions](https://master.libelektra.org/doc/decisions/high_level_api.md)
- [ ] get/set arrays containing standard types
- [ ] automatically updating variables (see  #825)
- [ ] smoothly integrate command-line arguments and environment variables  #1252

**Comment by markus2330** [comment]
I would suggest to focus on APIs with a clear user in mind, e.g. KDE/GNOME.
