### ISSUE TITLE
Release 0.8.21

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#1725]
# ToDo

- [ ] Fix [INI plugin](https://github.com/ElektraInitiative/blobs/tree/master/configs/ini)

# Won’t Fix

- [x] 10 Minute timeout problem ([Travis](https://travis-ci.org/ElektraInitiative/libelektra/jobs/314017443))
- [x] Fix build job [`elektra-gcc-configure-debian-jessie-minimal`](https://build.libelektra.org/jenkins/job/elektra-gcc-configure-debian-jessie-minimal/487/)
- [x] Fix build job [`elektra-multiconfig-gcc-stable`](https://build.libelektra.org/job/elektra-multiconfig-gcc-stable/126/)

# Done

## Build Server

- [x] Fix error “Couldn't find any revision to build”
- [x] Fix typo “Jenkin default” in the names of the build jobs displayed here at GitHub
- [x] Fix build job [`elektra-multiconfig-gcc47-cmake-options`](https://build.libelektra.org/job/elektra-multiconfig-gcc47-cmake-options/43)
- [x] Fix build job [`elektra-icheck`](https://build.libelektra.org/jenkins/job/elektra-icheck)

### INI

- [x] Check if INI works with
  - [x] Directory Value plugin: No 😢
  - [x] Null plugin: [Does not make sense](https://github.com/ElektraInitiative/libelektra/issues/1693#issuecomment-351472742) 
  - [x] Base 64 plugin: Yes 😌

## Sanitizer
- [x] [Add `4.*/bits/stl_tree.h` to Address Sanitizer blacklist](https://github.com/ElektraInitiative/libelektra/pull/1728) ([Issue Reference](https://github.com/ElektraInitiative/libelektra/issues/1713#issuecomment-350565953))

**Comment by markus2330** [comment]
Thanks for adding the TODO. Initially, such a TODO was handled by doc/todo/ROADMAP.md

But I am okay with migrating this TODO to the issue tracker. (You can remove doc/todo/ROADMAP.md if you want to)

**Comment by markus2330** [comment]
Thanks for collecting the TODOs.

I added "Fix typo "Jenkin default " in the names of the build jobs displayed here at GitHub"

**Comment by sanssecours** [comment]
> Fix typo "Jenkin default " in the names of the build jobs displayed here at GitHub"

Should be fixed now

> - 10 min no output problem? https://travis-ci.org/ElektraInitiative/libelektra/jobs/314017443
> - "ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job." in https://build.libelektra.org/jenkins/job/elektra-todo/1088/console

Hm, I think both of these issues were temporary problems. I will check if these problems occur again in the future.

**Comment by markus2330** [comment]
Thank you!

Yes, these errors do not always happen. To make "jenkins build all please" reliable and widely used, however, we should try to get rid of such glitches. Otherwise we might start to ignore erroneous build jobs and would miss the aim of continuous integration.

Obviously it is only a background task and the importance depends on how often the glitches occur.

**Comment by markus2330** [comment]
Thank you for your hard work!

**Comment by markus2330** [comment]
The release notes and homebrew are still open, however.
