### ISSUE TITLE
Metaissue - TODO's specification language enhancements

### ISSUE THREAD

**Issue by Piankero** [ElektraInitiative/libelektra#2224]
- [ ] Write a **default value calculation** plugin
- [x] Make the **network plugin** use domain names
- [x] Enhance the **network plugin** to also allow ports
- [ ] Enhance the **path plugin** to also check for access rights (rwx)
- [ ] The **range plugin** should also allow floating point numbers
