### ISSUE TITLE
Continuous Releases

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2530]
Currently the release process is done in many error-prone manual steps. The goal is, that only a button needs to be pushed for a release, doing everything as described in doc/todo/RELEASE

Furthermore, the releases should offer more to users:

- [x] having DEB packages (at least for Debian and Ubuntu) see #1802 
- [ ] having RPM packages (at least for CentOS) see #2519
- [ ] having a repo for statistical and informational purposes (see also doc/todo/RELEASE):
  - [ ] has output of ABI tests
  - [ ] list and sizes all files to be installed
  - [ ] changes of infos/status in the plugins
  - [ ] traces of tools
  - [ ] output of test cases
- [x] Windows binaries (mingw build job) https://build.libelektra.org/job/libelektra/job/master/lastSuccessfulBuild/artifact/artifacts/debian-buster-mingw-w64/elektra.zip
- [x] a docker container with Elektra installed (and one with WebUI, as already present scripts/docker/webui/)
- [ ] (low prior) other package managers (#1463)

An example of nice releases is Rocket Chat:
https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/2.15.1

**Comment by markus2330** [comment]
@Mistreated Some meta issue for the progress. What do you think is still realistic to be done?

**Comment by markus2330** [comment]
@Mistreated What is the current status?

**Comment by Mistreated** [comment]
> @Mistreated Some meta issue for the progress. What do you think is still realistic to be done?

Apparently I overlooked this..

> having DEB packages (at least for Debian and Ubuntu)

We already offer these packages, so I would say its done.

When it comes to other packages:

> having RPM packages (at least for CentOS)

I did not have success.

**Comment by markus2330** [comment]
What did you try, what did not work?

Are you confident with one of the tasks above that you could easily do it?

**Comment by Mistreated** [comment]
Before I went on holiday I looked Open Build Service and how to put down a spec file for RPM packages, since I've never done that.

> having RPM packages (at least for CentOS)

I would like to try to do it next week, although, I am not too confident.

**Comment by markus2330** [comment]
I mean any of the tasks above, maybe working more with docker brings more results?

**Comment by Mistreated** [comment]
> maybe working more with docker brings more results?

What did you have in mind?

**Comment by markus2330** [comment]
#2913

**Comment by mpranj** [comment]
The ubuntu bionic packages still have to be manually imported in the repo. We're missing something like a cronjob which does that.

For the debian packages we have fully automatic deployment when we push to master.

**Comment by markus2330** [comment]
Let us close this as this is not 1.0 critical anymore.
