### ISSUE TITLE
Meta-issue: Highlevel Code-generation

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#2680]
This is a list of open tasks related to the highlevel code-generation:

- [x] Documentation of code-generation framework
- [x] Documentation of `highlevel` (renamed from `elektra`) template [link](https://github.com/ElektraInitiative/libelektra/pull/2498#discussion_r282039773)
- [x] Fully implement or remove APIs related to contextual values
- [x] Improve documentation of examples
- [x] Write tutorial for using code-generation in an application
- [x] Minor issues from code reviews:
  - [x] Rename `elektra` template to `highlevel` [link](https://github.com/ElektraInitiative/libelektra/pull/2498#discussion_r282050553) + move header out of subdir
  - [x] Remove static helpKey from template [link](https://github.com/ElektraInitiative/libelektra/pull/2498#discussion_r282040562)
  - [x] Fix typos [link1](https://github.com/ElektraInitiative/libelektra/pull/2498#discussion_r282047708) [link2](https://github.com/ElektraInitiative/libelektra/pull/2498#discussion_r282004922) [link3](https://github.com/ElektraInitiative/libelektra/pull/2498#discussion_r281999964)
  - [x] Improve README script [link](https://github.com/ElektraInitiative/libelektra/pull/2498#discussion_r282051901)
  - [x] Remove unnecessary macro [link](https://github.com/ElektraInitiative/libelektra/pull/2498#discussion_r282038153)
- [x] Document lifetimes of pointers (also in highlevel API) #2774
- [x] Make tags configurable #2772
- [x] Option to disable complied-in spec.
- [x] Check for defaults and copy default into value (if empty) in `elektraOpen`.
- [x] Option to disable setter generation.
- [x] specload/quickdump option to use keyset without parent key in set.
  - [x] use this option in generated code to de-duplicate spec
- [x] required keys (via `spec` plugin, see also #2807)
- [x] allow changing of tag prefix
- [x] `specload`: don't write empty files
- [x] `minimal` spec validation
- [x] disable setters for struct_ref and structs containing struct_refs

---

Low priority:
- [x] Maybe use more real-worldy example instead of `tree`
- [x] Add exported CMake function for invoking code generation [link](https://github.com/ElektraInitiative/libelektra/pull/2498#discussion_r282050924)
- [ ] (If possible) convert examples READMEs to shell recorder [link](https://github.com/ElektraInitiative/libelektra/pull/2498#discussion_r282032234)
- [x] Add mustache library license to doc/THIRD-PARTY-LICENSES
- [ ] `restrict/write` to disable setter generation
- [x] `specload`: fix relative paths
- [x] `specload`: read directly from file

**Comment by markus2330** [comment]
Thank you for creating the issue!

**Comment by kodebach** [comment]
Right now the code-generation creates files which are marked as BSD-licensed.

https://github.com/ElektraInitiative/libelektra/blob/24f3278b2dd8989e50ce12042d00b6d79e1d199f/src/tools/kdb/gen/templates/elektra.h.mustache#L1-L7

Should that stay, or should only the template be under BSD license?

**Comment by markus2330** [comment]
Actually we could make them public domain. Then there should be definitely no problem for other projects which might have BSD-incompatible licenses (cannot mix their own code with BSD licensed code. I do not know if such a license exists, though.).

**Comment by kodebach** [comment]
I now changed the templates (not pushed yet), so that the [BSD zero clause license](https://spdx.org/licenses/0BSD.html) applies to the templates. This should ensure that the generated files can be used in anyway the user wants to. The generated files will also contain this license. As far as I understand, this should allow users to use the code in any project. As 0BSD doesn't even require that the license is retained.

I didn't make the files public domain, because that seems to be [hard to do right](https://softwareengineering.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense).

**Comment by kodebach** [comment]
I moved adding the mustache license to low priority, because none of the other non-BSD licences are mentioned in LICENSE.md right now.

**Comment by markus2330** [comment]
I added them in LICENSE.md now, please also add yours.
