### ISSUE TITLE
Bachelor Bakk Arbeit 00828630

### ISSUE THREAD

**Issue by raphi011** [ElektraInitiative/libelektra#2838]
This Issue tracks the progress of all tasks related to my bachelors thesis

- [x] Expose
- [x] Fix README typos #2803
- [x] Improve bindings tutorial #2928
- [x] Fix elektra-blob config/real-world data #2990
- [x] CI / Build Integration #2962
- [x] Go Bindings #2959
- [x] Vanity import for Go #3037
- [x] Thesis https://github.com/ElektraInitiative/abgaben/issues/5
- [x] Improve the documentation of ksAppendKey #3072
- [x] merge: add pkg-config file #3241  
- [x] Rewrite of elektrad in go  #2960
- [x] web-ui testen
- [x] Show documentation of elektrad on path "/" #3019
- [x] Flatten web tools folder hierarchy #2886
- [x] Web UI completely ignores the specification of configuration settings #2410
- [x] Make sure elektrad docker image works https://github.com/ElektraInitiative/libelektra/issues/3251
- [x] Fix crash #3370
- [x] update Readme #2886

- [x] after ubuntu packages: add to build server
- [ ] 3-way merge for Elektrad https://github.com/ElektraInitiative/libelektra/issues/3252
- [ ] web-ui: support new namespaces #3252
- [ ] Web UI throws unexplainable error #2408
- [ ] web instance is down #2913

**Comment by markus2330** [comment]
Thank you for creating the issue!

For "Go Bindings" you could give more details which header files you create bindings for (kdb.h, plugins in Go, notifications, ...). Great to see that you want to create a vanity import. We can also create the subdomain go.libelektra.org if you want.

>   Rewrite of configuration server in go

Currently, the server is called elektrad, the earlier we agree on how things are named the better. Do you want to change the name? "configuration server" is imho too generic.

Furthermore, at least the elektrad tasks of #1849 should be also fixed. Some improvements in the Web UI would also be very much welcomed (especially performance improvements and concurrent editing).

**Comment by raphi011** [comment]
> ... Great to see that you want to create a vanity import. We can also create the subdomain go.libelektra.org if you want.

That would be great!

> Currently, the server is called elektrad, the earlier we agree on how things are named the better. Do you want to change the name? "configuration server" is imho too generic.

elektrad is fine :)

> Furthermore, at least the elektrad tasks of #1849 should be also fixed. Some improvements in the Web UI would also be very much welcomed (especially performance improvements and concurrent editing).

I will take a look

**Comment by markus2330** [comment]
I created the A-entry go.libelektra.org

**Comment by raphi011** [comment]
> I created the A-entry go.libelektra.org

great, I cannot push to the master branch though.

Do I need to fork the doc repo or can I commit the index.html file differently? I may need to experiment and upload different versions because I'm not entirely sure how this is done for go.mod files in a git subdirectory.

**Comment by markus2330** [comment]
Creating Pull-Requests should work. Maybe ssh access is better then because content in the GitHub repo does not directly reflect to the repo on the webserver (I need to push there). Or even easier: why not simply redirect go.libelektra.org to a local webserver (using /etc/hosts) which you use to play around?

btw. please put the index.html in a subdir, otherwise it will be very confusing for people looking at doc.libelektra.org (it currently uses directory listings which do not work if there is a index.html)

**Comment by raphi011** [comment]
> Creating Pull-Requests should work. Maybe ssh access is better then because content in the GitHub repo does not directly reflect to the repo on the webserver (I need to push there). Or even easier: why not simply redirect go.libelektra.org to a local webserver (using /etc/hosts) which you use to play around?

good idea I'll try that

> btw. please put the index.html in a subdir, otherwise it will be very confusing for people looking at doc.libelektra.org (it currently uses directory listings which do not work if there is a index.html)

I've created a PR

BTW: the basic functionality of elektrad v2 already works :) I can point the web configuration interface to the new server and listing of keys / showing values works.

You can probably take a look at the code when you got time.

**Comment by markus2330** [comment]
As the remaining tasks already have their own issues, I close this issue. Thank you so much for your amazing work and we would love to see further contributions from you!
