### ISSUE TITLE
Jenkins: Retry Failed Builds

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#2967]
# Description

Currently the Jenkins build fails quite often for various reasons. This issue should list some of the problems that currently include:

- [x] failing [Maven builds](https://github.com/ElektraInitiative/libelektra/issues/2855),
- [ ] failing [Homepage builds](https://github.com/ElektraInitiative/libelektra/issues/2897), 
- [ ] [internal compiler errors](https://github.com/ElektraInitiative/libelektra/issues/2986), 
- [ ] CMake install failures,
- [ ] workspace removal failures,
- [x] Haskell build failures,
- [ ] APT install failures,
- [ ] [timeouts](https://github.com/ElektraInitiative/libelektra/issues/2984),
- [x] failing tests,
- [ ] [connection problems](https://github.com/ElektraInitiative/libelektra/issues/2999), and
- [ ] Git commit failures

.

# Failures

| Branch | Failure Reason | Failed Build Job/Stage |
|----------|-------------|-----------|
| [`PR #2932`](https://github.com/ElektraInitiative/libelektra/pull/2932) | [Maven build](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2932/12/pipeline) | `debian-unstable-clang-asan` |
| [`master`](http://github.com/ElektraInitiative/libelektra/commits/master) | [Homepage build](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/936/pipeline/) | Deploy Website |
| [`master`](http://github.com/ElektraInitiative/libelektra/commits/master) | [Homepage build](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/937/pipeline/) | Deploy Website |
| [`PR #2945`](https://github.com/ElektraInitiative/libelektra/pull/2945) | [Internal compiler error](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2945/4/pipeline) | `build-elektra-web-base` |
| [`master`](http://github.com/ElektraInitiative/libelektra/commits/master) | [Cmake install failure](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/939/pipeline/313) | `debian-stretch-full` |
| [`master`](http://github.com/ElektraInitiative/libelektra/commits/master) | [Workspace removal failure](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/940/pipeline/314) | Main builds |
| [`master`](http://github.com/ElektraInitiative/libelektra/commits/master) | [Workspace removal failure](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/941) | Main builds |
| [`master`](http://github.com/ElektraInitiative/libelektra/commits/master) | [Workspace removal failure](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/942) | Main builds |
| [`master`](http://github.com/ElektraInitiative/libelektra/commits/master) | [Workspace removal failure](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/943) | Main builds |
| [`master`](http://github.com/ElektraInitiative/libelektra/commits/master) | [Workspace removal failure](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/944) | Main builds |
| [`master`](http://github.com/ElektraInitiative/libelektra/commits/master) | [Workspace removal failure](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/945) | Main builds |
| [`PR #2945`](https://github.com/ElektraInitiative/libelektra/pull/2945) | [Haskell build failure](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2945/5/pipeline) | `debian-stretch-full-optimizations-off` |
| [`PR #2945`](https://github.com/ElektraInitiative/libelektra/pull/2945) | [APT install failed](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2945/6/pipeline) | `build-elektra-website` |
| [`PR #2932`](https://github.com/ElektraInitiative/libelektra/pull/2932) | [Maven build](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2972/1/pipeline) | `debian-unstable-clang-asan` |
| [`master`](http://github.com/ElektraInitiative/libelektra/commits/master) | [Timeout](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/949/pipeline) | `debian-stretch-full-mmap-asan` |
| [`PR #2975`](https://github.com/ElektraInitiative/libelektra/pull/2975) | [Timeout](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2975/1/pipeline/614) | `debian-buster-mingw-w64` |
| [`master`](http://github.com/ElektraInitiative/libelektra/commits/master) | [Homepage build](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/951/pipeline) | Deploy Website |
| [`master`](http://github.com/ElektraInitiative/libelektra/commits/master) | [Homepage build](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/952/pipeline) | Deploy Website |
| [`master`](http://github.com/ElektraInitiative/libelektra/commits/master) | [Timeout](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/957/pipeline/314) | `debian-buster-full` |
| [`master`](http://github.com/ElektraInitiative/libelektra/commits/master) | [Haskell build failure](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/959/pipeline) | `debian-stretch-full-ini` |
| [`master`](http://github.com/ElektraInitiative/libelektra/commits/master) | [Timeout](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/960/pipeline) | `debian-unstable-full` |
| [`master`](http://github.com/ElektraInitiative/libelektra/commits/master) | [Failing tests](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/963/pipeline/314) | `debian-buster-full` |
| [`master`](http://github.com/ElektraInitiative/libelektra/commits/master) | [Internal compiler error](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/964/pipeline) | `build-elektra-web-base` |
| [`master`](http://github.com/ElektraInitiative/libelektra/commits/master) | [Homepage build](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/965/pipeline) | Deploy Website |
| [`master`](http://github.com/ElektraInitiative/libelektra/commits/master) | [Homepage build](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/966/pipeline) | Deploy Website |
| [`master`](http://github.com/ElektraInitiative/libelektra/commits/master) | [Homepage build](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/970/pipeline) | Deploy Website |
| [`master`](http://github.com/ElektraInitiative/libelektra/commits/master) | [Homepage build](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/971/pipeline) | Deploy Website |
| [`PR #2998 `](https://github.com/ElektraInitiative/libelektra/pull/2998) | [Timeout](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2998/2/pipeline), [Connection problems](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2998/2/pipeline/611)  | `build-elektra-web-base`, `debian-buster-full-i386` |
| [`master`](http://github.com/ElektraInitiative/libelektra/commits/master) | [Maven build](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/980/pipeline) | `debian-unstable-clang-asan` |
| [`PR #2998 `](https://github.com/ElektraInitiative/libelektra/pull/2998) | [Timeout](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2998/3/pipeline) | `build-elektra-website-backend` |
| [`master `](http://github.com/ElektraInitiative/libelektra/commits/master) | [Connection problems](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/981/pipeline)  | `build-elektra-web-base` |
| [`master`](http://github.com/ElektraInitiative/libelektra/commits/master) | [Homepage build](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/983/pipeline) | Deploy Website |
| [`master`](http://github.com/ElektraInitiative/libelektra/commits/master) | [Maven build](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/1003/pipeline) | `debian-unstable-full-clang` |
| [`master`](http://github.com/ElektraInitiative/libelektra/commits/master) | [Git commit failure](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/1005/pipeline) | `buildPackage/debian/buster` |
| [`master`](http://github.com/ElektraInitiative/libelektra/commits/master) | [Git commit failure](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/1006/pipeline) | `buildPackage/debian/buster` |
| [`master`](http://github.com/ElektraInitiative/libelektra/commits/master) | [Git commit failure](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/1007/pipeline) | `buildPackage/debian/buster`, `buildPackage/debian/stretch` |
| [`master`](http://github.com/ElektraInitiative/libelektra/commits/master) | [Git commit failure](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/1008/pipeline) | `buildPackage/debian/buster` |
| [`master`](http://github.com/ElektraInitiative/libelektra/commits/master) | [Git commit failure](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/1009/pipeline) | `buildPackage/debian/buster` |

# Failing Tests

| Test                           | Location             | Times Failed |
| -------------------------------------- | --------------------- | ------------ |
| `check_external_example_codegen_econf` | `debian-buster-full` | 1            |
| `check_external_example_codegen_menu`  | `debian-buster-full` | 1            |
| `check_external_example_codegen_tree`  | `debian-buster-full` | 1            |
| `check_external_example_highlevel`     | `debian-buster-full` | 1            |
| `check_spec`                           | `debian-buster-full`  | 1            |
| `testkdb_ensure`                       | `debian-buster-full` | 1            |

**Comment by markus2330** [comment]
Thank you for collecting the issues!

For the maven builds we already have an issue: #2855

**Comment by sanssecours** [comment]
> For the maven builds we already have an issue: #2855

I know 😊. I already added a link in the issue description.

**Comment by markus2330** [comment]
For the Haskell problems we can remove the haskell bindings/plugins. They are not maintained anyway.

**Comment by markus2330** [comment]
Haskell will be removed in  #3017

**Comment by markus2330** [comment]
The failures with `docker pull` failing in the website stage occurs quite often now.

**Comment by Chemin1** [comment]
I just got connection problems for build-elektra-web-base, too.
```
3d070e3209ce: Retrying in 1 second

error creating overlay mount to /home/_docker/overlay2/e9563564b9365114c47d90b7e8d307565225097a525e6b1b866a2da2877b2aa8/merged: device or resource busy

script returned exit code 1
```

[This is a full log.](https://github.com/ElektraInitiative/libelektra/files/3702311/jenkinsDockerPush.txt)

**Comment by Chemin1** [comment]
> The failures with `docker pull` failing in the website stage occurs quite often now.

Is this all the retrying and waiting after `Pulling from build-elektra-web-base` ([log](https://github.com/ElektraInitiative/libelektra/files/3732623/log.txt))? 

Additionally, I think this error is new: `test_service_convertengine` fails during `Starting build/hub.libelektra.org/build-elektra-website-backend` ([log 2](https://github.com/ElektraInitiative/libelektra/files/3732627/log.1.txt))

**Comment by markus2330** [comment]
Yes, I agree test_service_convertengine is not reported here yet. Actually we can disable the test as the service is not modified anyway.

@sanssecours is there some procedure how to add new tests in the above list?

**Comment by sanssecours** [comment]
> @sanssecours is there some procedure how to add new tests in the above list?

Nope. I already gave up on modifying the list, since the Jenkins build fails too often. I would recommend we just open an issue for each specific problem.

**Comment by markus2330** [comment]
For issues related to source code I agree. For the issues related to docker/jenkins instability it is enough to collect issues here as it is very limited what we can do next to the migration we already do but unfortunately takes longer as expected. It would be nice if @Mistreated could give more information about the status, maybe in #160.

**Comment by markus2330** [comment]
> Additionally, I think this error is new: test_service_convertengine fails during Starting build/hub.libelektra.org/build-elektra-website-backend (log 2)

Can you please report that separately? The fix is to disable the tests.

**Comment by Chemin1** [comment]
> Can you please report that separately?

Done, see #3086

**Comment by markus2330** [comment]
I think our best guess to make our lives much easier is to "fix" these problems using https://wiki.jenkins.io/display/JENKINS/Naginator+Plugin

Then Jenkins will restart failed jobs several times. I think we could try 5 restarts before giving up?

@Mistreated Can you implement this also on the old server? Or is this too risky?

Before we implement this, however, we need the new Jenkins Node as otherwise the queue will get too long.

**Comment by Mistreated** [comment]
After a bit of struggling I managed to add a new Jenkins Node.

> Before we implement this, however, we need the new Jenkins Node as otherwise the queue will get too long.

The old server is overloaded in my opinion, but we can try I guess..

**Comment by sanssecours** [comment]
> After a bit of struggling I managed to add a new Jenkins Node.

Thank you for adding the new Jenkins node. I disabled the node for now, since [it seems to break the build](https://github.com/ElektraInitiative/libelektra/issues/160#issuecomment-544483177).

**Comment by Mistreated** [comment]
I updated the node. It should work now. If something goes wrong you can update me here again.

**Comment by sanssecours** [comment]
> If something goes wrong you can update me here again.

Looks like [`docker pull` fails on `hetzner-jenkins1`](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-3065/19/pipeline/337), since the node has not enough free space:

> Cannot contact hetzner-jenkins1: hudson.remoting.RequestAbortedException: java.io.IOException: Unexpected termination of the channel
> failed to register layer: ApplyLayer exit status 1 stdout:  stderr: write /usr/lib/git-core/git-credential-store: disk quota exceeded


.

**Comment by Mistreated** [comment]
> Looks like docker pull fails on hetzner-jenkins1, since the node has not enough free space:

Node updated.

**Comment by sanssecours** [comment]
Build jobs on [`hetzner-jenkins1` seem to fail](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/95/pipeline/613/), because of permission related problems:

> Resource: Could not create directory '/.config'. Reason: Permission denied. Identity: uid: 47000, euid: 47000, gid: 47000, egid: 47000

.

**Comment by Mistreated** [comment]
I updated the Node, again, there shouldnt be any permission issues anymore.

**Comment by Mistreated** [comment]
Why does Jenkins wants to build a '/.config' and not just '.config' directory? 
There is a .config directory inside '/home/jenkins/' but he wants to make .config folder in '/'. 

I dont think user 'jenkins' should be able to do that.

**Comment by markus2330** [comment]
@Mistreated please also make a PR to actually test if the builds work now.

> Why does Jenkins wants to build a '/.config' and not just '.config' directory?
There is a .config directory inside '/home/jenkins/' but he wants to make .config folder in '/'.

This might happen if the home directory of the user is /. Did you look into /etc/passwd, maybe something is wrong there?

**Comment by Mistreated** [comment]
> This might happen if the home directory of the user is /. Did you look into /etc/passwd, maybe something is wrong there?

'jenkins:x:47000:47000::/home/jenkins:/bin/sh'

All looks fine, even in the logs of the node:

'HOME='/home/jenkins' '
'NOTE: Relative remote path resolved to: /home/jenkins/.'

**Comment by markus2330** [comment]
It would be easier to debug to see a PR with the whole log.

**Comment by sanssecours** [comment]
> Master node is down.

Thank you for the information. I deleted all log information for old pull requests and reenabled the node. Unfortunately the amount of free space on the Jenkins master is still very low (~ 3.9G).

**Comment by markus2330** [comment]
@Mistreated I moved the discussion about the hetzner node to #3138. This issue is about temporary failures in the build server, not about wrong setup of the build server.

**Comment by sanssecours** [comment]
Looks like building Docker images [does not work on `hetzner-jenkins1`](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-3099/21/pipeline):

```
stderr: error: could not lock config file .git/config: Disk quota exceeded
```

. I disabled the node.

**Comment by Mistreated** [comment]
It just `Disk quota exceeded` , I did not want to overkill it with memory. I cleaned it up now. Its up again.

**Comment by markus2330** [comment]
Two more tests that happen:

```
 27/134 MemCheck  #23: testcpp_contextual_thread ........***Exception: Other  2.59 sec
Running main() from /opt/gtest/googletest/src/gtest_main.cc
[==========] Running 8 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 8 tests from test_contextual_thread
[ RUN      ] test_contextual_thread.instanciation

/home/jenkins/workspace/libelektra_PR-3168-L5JHIPUUQR3TWFGKHQIDK6HHW6QAMSQXWJC5ZUZMBLDMLTYA2ENA@2/src/bindings/cpp/tests/testcpp_contextual_thread.cpp:70: Failure

Expected equality of these values:
  ks.lookup ("user/hello").getString ()
    Which is: "8"
  "5"
terminate called without an active exception
```

```
60/254 Test  #57: testio_glib .................................***Failed    5.08 sec

BINDING TEST-SUITE

==================

test basics
test idle
test timer
testTimerShouldCallbackOnce (warning): measured 316ms, expected 250ms - deviation 66ms.
testTimerShouldCallbackAtIntervals (warning): measured 343ms, expected 250ms - deviation 93ms.
testTimerShouldCallbackAtIntervals (warning): measured 322ms, expected 250ms - deviation 72ms.
testTimerShouldCallbackAtIntervals (warning): measured 338ms, expected 250ms - deviation 88ms.
../src/bindings/io/test/test_timer.c:273: error in testTimerShouldChangeInterval: timer was not called the required amount of times
test file descriptor
test mix
```

**Comment by markus2330** [comment]
Yet another error in https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/12/pipeline/

```
Step 12/31 : RUN curl -o cppcms-${CPPCMS_VERSION}.tar.bz -L         "https://sourceforge.net/projects/cppcms/files/cppcms/${CPPCMS_VERSION}/cppcms-${CPPCMS_VERSION}.tar.bz2/download"     && tar -xjvf cppcms-${CPPCMS_VERSION}.tar.bz     && mkdir cppcms-${CPPCMS_VERSION}/build     && cd cppcms-${CPPCMS_VERSION}/build     && cmake ..     && make -j ${PARALLEL}     && make install     && cd /app/deps     && rm -Rf cppcms-${CPPCMS_VERSION}

 ---> Running in f5ed5e42a480

curl: (92) HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)

The command '/bin/sh -c curl -o cppcms-${CPPCMS_VERSION}.tar.bz -L         "https://sourceforge.net/projects/cppcms/files/cppcms/${CPPCMS_VERSION}/cppcms-${CPPCMS_VERSION}.tar.bz2/download"     && tar -xjvf cppcms-${CPPCMS_VERSION}.tar.bz     && mkdir cppcms-${CPPCMS_VERSION}/build     && cd cppcms-${CPPCMS_VERSION}/build     && cmake ..     && make -j ${PARALLEL}     && make install     && cd /app/deps     && rm -Rf cppcms-${CPPCMS_VERSION}' returned a non-zero code: 92

script returned exit code 92
```

I am afraid https://wiki.jenkins.io/display/JENKINS/Naginator+Plugin is the only bigger step forwards.

Unfortunately, it will not fix the problems for Travis or Cirrus.

**Comment by Chemin1** [comment]
Do we updated "Times failed" in the start post? `check_external_example_codegen_econf`is happening quite often currently.

**Comment by markus2330** [comment]
Trying to update the start post or trying to fix all these issues is hopeless. We need automatic retrying. I hope @Mistreated will implement this soon on our new server.

**Comment by markus2330** [comment]
What do you think about #3224?

**Comment by markus2330** [comment]
Problems are solved now. Please open new issues if build still fail.
