### ISSUE TITLE
Next steps in LCDproc

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3041]
@kodebach wrote in  #2815:

- [ ] Using the `ini` plugin doesn't work, because of the multiline `description` metakeys. (I switched to `ni` for now, but its file format is not ideal).
- [ ] Parts of the specifications are still commented out because of the max plugins issue.
- [ ] Not all drivers are updated. The specification is based on the old example `LCDd.conf`; not all config keys for drivers are included. The updated drivers have a full specification.
- [ ] Once all drivers are updated, the rather big specification for `LCDd` will probably slow down the server start-up time as well as any (cascading) `kdb` operation that calls the `spec` plugin on the relevant mountpoint. Dynamically enabling/disabling parts of the specification would be nice, although I don't see any way to do this right now.
- [ ] Improving the `spec` plugin performance would also be nice, but again, I don't know how.
- [ ] Various known issues with the `kdb` tool that make using it hard. Especially the fact that `kdb set -N user <cascading-key>`, may result in a broken configuration (because of the `origvalue` metadata).

**Comment by markus2330** [comment]
>  Using the ini plugin doesn't work, because of the multiline description metakeys. (I switched to ni for now, but its file format is not ideal).

@bauhaus93 is working on it with the new TOML format

> Parts of the specifications are still commented out because of the max plugins issue.

@vLesk is working on it

>  Not all drivers are updated. The specification is based on the old example LCDd.conf; not all config keys for drivers are included. The updated drivers have a full specification.

Yes, some more drivers would be nice, @bauhaus93 said he will add support for one driver.

> Various known issues with the kdb tool that make using it hard. Especially the fact that kdb set -N user <cascading-key>, may result in a broken configuration (because of the origvalue metadata).

@kodebach Which is the issue number for this?

**Comment by kodebach** [comment]
> Yes, some more drivers would be nice, @bauhaus93 said he will add support for one driver.

Adding new drivers is not much of a problem. It's quite straight forward, I also wrote [instructions for it](https://github.com/ElektraInitiative/lcdproc/blob/e35c481e2e3fceef401e82e5694f5b4197cbb41d/docs/elektra/drivers.md). The problem is more testing everything still works.

> Which is the issue number for this?

We discussed it in #3020 and #2700. I have not yet investigated, where the `origvalue` metakey even comes from, as it should be removed by `keySetString`. Possibly the `type` plugin is called multiple times on keysets that contain the same keys?

The fact is that this happens:

```sh
# TODO: build and install Elektra
# TODO: build and install LCDproc
# TODO: run LCDproc post-install.sh to mount spec etc

LCDd
#> An error occurred while initializing elektra: Validation Semantic: Required key /sw/lcdproc/lcdd/#0/current/server/drivers/#0 is missing.

# NOTE: That is expected, no default driver is set up.

# set driver

kdb set -N user /sw/lcdproc/lcdd/#0/current/server/drivers/#0 @/curses/#0
#> kdb set -N user /sw/lcdproc/lcdd/#0/current/server/drivers/#0 @/curses/#0
#> Create a new key user/sw/lcdproc/lcdd/#0/current/server/drivers/#0 with string "@/curses/#0"

# Check that this doesn't actually do anything unexpected:

cat $(kdb file user/sw/lcdproc/lcdd/#0/current)
#> ;Ni1
#> ; Generated by Nickel Plugin using Elektra (see libelektra.org).
#> 
#> server/driverpath = /usr/local/lib/lcdproc/
#> server/drivers/#0 = @/curses/#0
#> 
#> [server/driverpath]
#>  check/type = string
#>  description = Select the LCD size
#>  default = $ORIGIN/drivers/
#>  type = string
#> 
#> [server/drivers/#0]
#>  check/type = string
#>  type = string
#>  require = 

# Looks fine...
# Try running LCDd just to be sure (with -f, so CTRL+C fully kills the server)
LCDd -f

# NOTE: you should see the curses interface, press CTRL+C to close
```

Now the interesting part:
```sh
kdb set -N user /sw/lcdproc/lcdd/#0/current/server/foreground true
#> Using name user/sw/lcdproc/lcdd/#0/current/server/foreground
#> Create a new key user/sw/lcdproc/lcdd/#0/current/server/foreground with string "true"

LCDd -f
#> An error occurred while initializing elektra: Installation: The key 'user/sw/lcdproc/lcdd/#0/current/server/foreground' was already normalized by a different plugin. Please ensure that there is only one plugin active that will normalize this key
```

That is odd, it seems something sets `origvalue` before the `type` plugin runs.
Even more interesting, here is the config file again:

```sh
cat $(kdb file user/sw/lcdproc/lcdd/#0/current)
#> ;Ni1
#> ; Generated by Nickel Plugin using Elektra (see libelektra.org).
#> 
#> server/driverpath = /usr/local/lib/lcdproc/
#> server/foreground = true
#> server/drivers/#0 = @/curses/#0
#> 
#> [server/driverpath]
#>  check/type = string
#>  description = Select the LCD size
#>  default = $ORIGIN/drivers/
#>  type = string
#> 
#> [server/foreground]
#>  opt/arg = none
#>  opt/long = foreground
#>  check/type = boolean
#>  opt = f
#>  description = The server will stay in the foreground if set to yes
#>  default = 0
#>  type = boolean
#> 
#> [server/drivers/#0]
#>  check/type = string
#>  type = string
#>  require = 

# Also save this for later:
cp  $(kdb file user/sw/lcdproc/lcdd/#0/current) /tmp/lcdproc-backup.ini
#> 

# And to verify the spec wasn't modified:
kdb lsmeta spec/sw/lcdproc/lcdd/#0/current/server/foreground
#> check/type
#> default
#> description
#> opt
#> opt/arg
#> opt/long
#> type

# NOTE: normally I would just show the `kdb lsmeta user/...` output, but that is after `type` runs AFAIK, so it doesn't help much.
```

As you can see, there is `origvalue` is not stored in the file. If I remember correctly, this was different with the `ini` plugin. At least I am fairly certain that the `origvalue` was present in the file at some point.

Now for the solution:

```sh
kdb rmmeta user/sw/lcdproc/lcdd/#0/current/server/foreground origvalue
#> 

# It works again....
LCDd -f

# NOTE: you should see curses stuff again
```

What happend? We call `diff -u /tmp/lcdproc-backup.ini $(kdb file user/sw/lcdproc/lcdd/#0/current)` to find out:

```diff
--- /tmp/lcdproc-backup.ini	2019-10-07 19:26:32.953276477 +0200
+++ /home/klemens/.config/LCDd.conf	2019-10-07 19:26:53.477351608 +0200
@@ -2,7 +2,7 @@
 ; Generated by Nickel Plugin using Elektra (see libelektra.org).
 
 server/driverpath = /usr/local/lib/lcdproc/
-server/foreground = true
+server/foreground = 1
 server/drivers/#0 = @/curses/#0
 
 [server/driverpath]
```

The `rmmeta` call removed `origvalue` between `kdbGet` and `kdbSet` and thereby disabled the restore procedure of `type`. That is why the value `1` is stored in the key. This in turn means that `type` doesn't have to normalize and doesn't create `origvalue`.

This more or less confirms my suspicion that `type` is called twice during `kdbGet`, both times with a KeySet containing `user/sw/lcdproc/lcdd/#0/current/server/foreground`. It then second call then gets confused by the `origvalue` from the first call.

**Comment by markus2330** [comment]
> Adding new drivers is not much of a problem. It's quite straight forward, I also wrote instructions for it. The problem is more testing everything still works.

As discussed with @haraldg this will be mostly community effort.

> I have not yet investigated, where the origvalue metakey even comes from, as it should be removed by keySetString

Moved to #3056.

**Comment by markus2330** [comment]
Moved to https://github.com/ElektraInitiative/lcdproc/issues/13
