### ISSUE TITLE
testshell_markdown_tutorial_crypto: fails on macOS

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#3806]
## Steps to Reproduce the Problem

Fails on all macOS CI runners (Cirrus-CI, GitHub Actions). Notably GnuPG has been updated to 2.3.x and libgcrypt to 1.9.3.
See an [example](https://cirrus-ci.com/task/5540780325470208) run.

I was not yet able to reproduce the issue locally.

## Expected Result

Test should succeed.

## Actual Result

Truncated log:

```
1/1 Test #185: testshell_markdown_tutorial_crypto ...***Failed    4.75 sec

CMD: kdb mount test.ini user:/tests crypto "crypto/key=$(kdb gen-gpg-testkey)" base64 ini
RET: 7
=== FAILED return value does not match expected pattern 0
STDERR: The command /private/var/folders/sr/b58hwhtj0jbcf4r09zmg0wlc0000gn/T/cirrus-ci-build/build/bin/kdb-full mount terminated unsuccessfully with the info:
The provided plugin configuration is not valid!
Errors/Warnings during the check were:
Sorry, module crypto issued the error C01330:
Plugin Misbehavior: GPG failed with return value 512. gpg: (null): skipped: No public key
gpg: [stdin]: encryption failed: No public key

Mountpoint: /
Configfile: 
At: ../src/plugins/crypto/gpg.c:788

Please report the issue at https://issues.libelektra.org/
ERROR: C01330
```

## System Information

- Elektra Version: master
- Operating System: macOS
- Versions of other relevant software: GnuPG 2.3.1, libgcrypt 1.9.3

## Further Log Files and Output
Full test log: [tests.log.txt](https://github.com/ElektraInitiative/libelektra/files/6363698/tests.log.txt)

## Tasks

- [ ] fix issue? (or wait for upstream fix)
- [ ] use updated GnuPG series 2.3.x (undo **parts** of #3809)
- [ ] implement missing error handling of `gpgme_op_createkey` in tool `gen-gpg-testkey`

**Comment by petermax2** [comment]
I don't have an OS X environment available for testing and ArchLinux still uses `gnupg 2.2.27-1` although it has been flagged as outdated. I'll have to compile the new version of gnupg myself and check inside a VM. I'll definitely have a look at it but it will take some time.

**Comment by mpranj** [comment]
@petermax2 no worries, but thanks for taking a look!

Maybe even a macOS environment would not help. On my machine I can not reproduce it. It might be isolated to the CI images.

My system has a .gnupg dir with configured keys and a keyring etc. Is it possible that the issue appears only on systems where the .gnupg dir does not exist yet?

**Comment by petermax2** [comment]
Just by looking at the logs it seems like the key-generation tool does not generate anything useful. Might be a problem with `gpgme` and the new `gnupg` version. If you run `gen-gpg-testkey`, do you get a key as output?

**Comment by petermax2** [comment]
Not sure how it looks on MacOS but in an ArchLinux VM with new gnupg installed, I get

    [vagrant@archlinux build]$ ./bin/gen-gpg-testkey 
    Segmentation fault (core dumped)
    [vagrant@archlinux build]$ 

@mpranj Can you maybe reproduce the crash on Mac OS?

**Comment by mpranj** [comment]
Can't reproduce the segfault. I get this on the machine where it fails:
```
$ ./bin/gen-gpg-testkey
(null)%
```
On the machines where it works, it seems like I get the key fingerprint. 👀

**Comment by petermax2** [comment]
OK, "(null)" is somewhat better than segfault :laughing:  but not what we need. The tool is supposed to write the fingerprint of the test-key to stdout. Thank you for confirming it, now we know the root of the problem!

**Comment by petermax2** [comment]
The exact cause of the problem is the call of `gpgme_op_createkey` in tool `gen-gpg-testkey`. The function call to gpgpme fails with the message "General error".

The creation of the GPG key fails, the error handling of `gpgme_op_createkey` is missing (oops, my bad... sorry!), which leads to segfault/"(null)" output if the elektra test key is missing.

If the tool fails to create/provide a key, all markdown tests concerning the crypto, fcrypt, gpgme plugins will most likely fail as well.

**Comment by mpranj** [comment]
I pinned GnuPG to 2.2x via #3809 and it works for now.

Does it make sense to report the issue upstream?

**Comment by markus2330** [comment]
Of course, it is always nice to give upstream some feedback.

@petermax2 can you maybe do this?

**Comment by petermax2** [comment]
> @petermax2 can you maybe do this?

I am working on it. My account at the bug reporting tool is still pending.

**Comment by petermax2** [comment]
I reported the issue [here](https://dev.gnupg.org/T5422).
