### ISSUE TITLE
machinekit integration

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#388]
- [x] type plugin with types as needed for machinekit (testing+tutorial)
- [x] mainloop integration
- [ ] rename/ini should work together with dbus/logchange
- [X] globbing copy for override #378 (fixed by profile plugin)
- [X] rename does not work in write direction #404 #485
- [X] ini array does not work in write direction #355
- [X] multiple INI entries to array #355 
- [X] spec plugin to copy metadata from spec
- [X] rename: support uppercase #387 fixed by #390
- [X] kdb editor, see #386 

@strahlex: please add if something is missing in this list and how to prioritize? Is something maybe not needed anymore?

**Comment by markus2330** [comment]
@strahlex Does it matter to machinekit in anyway if POSIX functionality is used (e.g. fnmatch, regex,..)

**Comment by markus2330** [comment]
@mhaberler Would be good if you can have a look, too.

**Comment by strahlex** [comment]
priority 1: INI array
priority 2: spec
priority 3: globbing
type plugin: existing types can easily be reused, not sure if a additional plugin is necessary
kdb edit: I would call it "kdb sync"

**Comment by strahlex** [comment]
I see no reason why POSIX functionality shouldn't be used.

**Comment by markus2330** [comment]
Should be resolved for this release, types to be discussed later.

**Comment by strahlex** [comment]
Thanks, will take a look at it.

**Comment by markus2330** [comment]
Seems like 3 issues are still open and we closed 2 issues (new profile plugin and improved rename plugin)
