### ISSUE TITLE
Embedded libautomation requirements

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3909]
must:
- [x] OpenWRT package #3898
- [ ] ini-like, human-writable plugin (like TOML) as default #3478 
- [x] internalnotification with ev #3906 #3907 
- [x] everything in C99 (no C++ runtime) #3111
- [X] polling (repeated kdb)
- [ ] make cache suitable for flash storage #3944

should:
- [ ] TOML with specs #3478 
- [X] specification with [paths](https://www.libelektra.org/plugins/path), ints 

nice to have:
- [ ] specification with floats (check on ARM? test with internalnotification)
- [ ] 3-way merge in C #3030 #2417 #3131 

unclear:
- [ ] directoryvalue in C #3912

discarded:
- [ ] WebUI (unrealistic)

**Comment by markus2330** [comment]
Let us focus on KDE&GNOME.
