### ISSUE TITLE
implement semantics of meta:/ keys

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4054]
- [ ] no meta-data can be contained (as meta-meta data lives in spec:/)
- [ ] no binary values are allowed (as they require meta-data)
- [ ] value must be read-only (as meta-data might be shared between keys)
- [ ] name must be read-only
@kodebach wrote:
> Keys added via `keySetMeta(k, ...)` are automatically locked. Keys added via `ksAppendKey(keyMeta(k), ...)` are not locked. This is a known issue and will be fixed, by making keys with a `meta:/` name automatically read-only.

Did I forget some semantics of meta:/ keys?

**Comment by kodebach** [comment]
Everything you mentioned would be implemented in `Key`. But related to this there is also:

- [ ] A `KeySet` can either contain only `meta:/` keys, or no `meta:/` keys.

Not sure, if we wanna track this here, or in a different issue (e.g. #3598)

**Comment by kodebach** [comment]
ping
