### ISSUE TITLE
Milestones kdb-record

### ISSUE THREAD

**Issue by atmaxinger** [ElektraInitiative/libelektra#4463]
This issue is for tracking my milestones

- [x] M1 - 1.10.2022 - finalized use cases/begin of implementation. Global plugins should work in new-backend branch.
- [ ] M2 - 12.12.2022 - working implementation/begin of case studies. Submitted introduction, methodology and description of case studies for review.
- [ ] M3 - 6.2.2023 First Draft of Thesis

**Comment by markus2330** [comment]
Please also write for M2 which parts of the thesis you want to submit, e.g. introduction and methodology.

About Implementation: I assume everything related to new-backend is M1, everything else is M2 and M3 is for left-overs?

**Comment by atmaxinger** [comment]
Hmm yes it would probably make sense to have the Methodology, Introduction and the description of the Case Studies finished by M2.

Regarding the Implementaion: originally everything including new-backend was planned for M2, but if we want to merge it by October then yes M1 would make much more sense for reparing the current global plugins.

Yes, at M3 implementation should be completely finished, including all bugs that I found during the execution of the case studies.

**Comment by markus2330** [comment]
Sounds good to me! :rocket:
