### ISSUE TITLE
Update docu about how to write release notes and fix commit msg from elektrabot

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/libelektra#4990]
I investigated a bit (with the help of @atmaxinger) why the libelektra release notes are not fully populated.

## Steps to Reproduce the Problem

Follow RELEASE.md

## Expected Result

Fully populated release notes.

## Actual Result

Unfinished [release notes](https://github.com/ElektraInitiative/libelektra/blob/master/doc/news/2023-08-04_0.11.0.md).
Note the `<<scripts/generate-news-entry>>`.

## Tasks

- [ ] fix broken regex (see below)
- [ ] change commit msg: "release: add hashsums and statistics to release notes" to be more true
- [ ] The written command there is also wrong: `scripts/git-release-stats 0.11.0.VER-1 0.11.0` must be `scripts/git-release-stats v0.10.0 v0.11.0 `
- [ ] But they need to manually improved anyway (there are a few duplicates and we don't need to honor Restyled.io). So IMHO it actually makes sense to do this manually. So we only need to improve the documentation about that.
- [ ] "This release did not happen yet." also needs to be manually removed.
- [ ] The reason that it is not shown in RSS feed is probably that `scripts/generate-news-entry` also wasn't executed yet.

**Comment by markus2330** [comment]
Thank you for looking into it. Don't use too much time on it, we can also do it manually. Statistics are not the most important thing.

**Comment by markus2330** [comment]
Or maybe someone else knows what is happening why the release notes were not updated, maybe @robaerd?

Or @tmakar can you maybe answer the question if the release note were fully populated for 0.10.0 or did you do something manually?

**Comment by 4ydan** [comment]
I found this regex a bit suspicious, but it doesnt solve the problem.
https://github.com/ElektraInitiative/libelektra/blob/dbbe4ae4f669c322a8f95f59112d3f5fc370bbd9/scripts/release/release.sh#L123
0-9 probably does not work for 0.11 ?

**Comment by robaerd** [comment]
> Or maybe someone else knows what is happening why the release notes were not updated, maybe @robaerd?

As far as I can tell everything worked as it was supposed to?
Replacing `<<scripts/generate-news-entry>>` was IIRC always a manual pre-release step done by @mpranj.

> I found this regex a bit suspicious, how does it work for 0.10 and 0.11 when they are not in 0-9?
> Or does it only match the first digit?

Although the regex is wrong and should be fixed, it still worked during the release.
The last `.` matches the second digit of the two-digit version number 0.1`1` and `[0-9]*` of the regex is just ignored.

**Comment by mpranj** [comment]
> Replacing <<scripts/generate-news-entry>> was IIRC always a manual pre-release step

Yes it was. I'm not sure if someone automated it in the mean time though.

**Comment by 4ydan** [comment]
> As far as I can tell everything worked as it was supposed to?

I see, so it is a manual step and we can close this.
Thank you for the swift replies.

**Comment by markus2330** [comment]
I see, thx for the answers!

I agree it is a bit confusing that elektrabot pushes a commit with "release: add hashsums and statistics to release notes" when the statistics actually need to be added manually.

The written command there is also wrong: `scripts/git-release-stats 0.11.0.VER-1 0.11.0` must be `scripts/git-release-stats v0.10.0 v0.11.0 `

Given the v0.11.0 tag on dbbe4ae4f669c322a8f95f59112d3f5fc370bbd9, generating the statistics works for me:

```
Number commits: 491
      1 Author: Adi <53004139+4ydan@users.noreply.github.com>
      1 Author: Maximilian Irlinger <maxi6594@gmail.com>
      1 Author: Mihael Pranjic <mpranj@limun.org>
      1 Author: Stefan Hanreich <stefanhani@gmail.com>
      2 Author: Klemens Böswirth <k.boeswirth+git@gmail.com>
      2 Author: tucek <tucek@hellwach.at>
      3 Author: Aydan Namdar Ghazani <e11709245@student.tuwien.ac.at>
      3 Author: Michel Tucek <michael@tucek.eu>
      4 Author: elektrabot <elektrabot@libelektra.org>
      7 Author: 0x6178656c <115062452+0x6178656c@users.noreply.github.com>
      8 Author: Hannes Laimer <hannes.laimer@tuwien.ac.at>
     10 Author: tmakar <tmakar23@gmail.com>
     18 Author: Markus Raab <markus2330@users.noreply.github.com>
     38 Author: Restyled.io <commits@restyled.io>
     68 Author: Florian Lindner <florian.lindner@student.tuwien.ac.at>
    120 Author: Richard Stöckl <richard.stoeckl@aon.at>
    204 Author: Maximilian Irlinger <max@maxirlinger.at>
 292 files changed, 20437 insertions(+), 2288 deletions(-)
```

But they need to manually improved anyway (there are a few duplicates and we don't need to honor Restyled.io). So IMHO it actually makes sense to do this manually. So we only need to improve the documentation about that.

"This release did not happen yet." also needs to be manually removed.

The reason that it is not shown in RSS feed is probably that `scripts/generate-news-entry` also wasn't executed yet.

@atmaxinger what was the error you got from `scripts/git-release-stats v0.10.0 v0.11.0 `? Can you fix the remaining problems and update the docu about that?
