### ISSUE TITLE
Shell Recorder Problems

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#944]
# Overview
- [ ] prefix with tmp if absolute path  #1139
- [ ] prefix with constant (tests?) and unique id on any path (file path) #1753
- [ ] check if only allowed Elektra paths are used (like /examples, /tests, and /tutorials?) #1753 
- [ ] check for left over files (and fail if there are)
- [ ] STDERR hidden
- [ ] diffs on exported symbols
- [ ] might add keys (global plugins)
- [ ] shell recorder should have a way to specify (plugin) dependencies needed to run the test case
- [ ] Cannot iterate over multiple similar plugins (if available) e.g. kdb mv test cases for git resolver and other resolver.
- [x] support HEREDOC
- [x] cleanup tmp file (protocol)
- [x] should fail if backup (export in line 52) could not done be successfully
- [x] should check if KDB is left with any changes that were not reverted by backup+restore (like tests/shell/run_all.sh does)
- [x] rename "Mountpoint:" to "Backup-and-restore:"
- [x] testshell_* testcases do not execute anything, protocol file is empty.
- [x] might remove keys
- [x] protocol files not removed
- [x] sed command might not be terminated correctly (sed: -e Expression #1, Character 86: `s'-command not terminated) caused by data in system/tests/dump when running testshell_db_changes

# Describe what you wanted to do

Run shell recorder tests without necessary plugins.
# Describe what you expected

Get some clear info that plugin is missing
# Describe what actually happened

Output did not show the error at all (STDERR only in protocol).
Ideally we should have some way to specify which plugins a shell-recorder tests and jump over the testcase.

In the protocol files there are many differences of the exported function pointers shown. Why do they not lead to errors?
# System Information
- Elektra Version: master
# Further Log Files and Output

```
CMD: get /sw/org/myapp/#0/current/testkey
RET: 1
STDERR: Did not find key3 Warnings were issued:
 Warning number: 1
        Description: could not load module, dlopen failed
        Ingroup: modules
        Module: dl
        At: /home/jenkins/workspace/workspace/elektra-gcc-configure-xdg/src/libs/loader/dl.c:86
        Reason: of module: libelektra-list.so, because: libelektra-list.so: cannot open shared object file: No such file or directory
        Mountpoint: system/elektra
        Configfile: kdbOpen(): mountGlobals
 Warning number: 64
        Description: could not load plugin in process plugin
        Ingroup: modules
        Module: kdb
        At: /home/jenkins/workspace/workspace/elektra-gcc-configure-xdg/src/libs/elektra/mount.c:322
        Reason: list
        Mountpoint: system/elektra
        Configfile: kdbOpen(): mountGlobals
 Warning number: 139
        Description: failed to mount global plugins
        Ingroup: kdb
        Module: 
        At: /home/jenkins/workspace/workspace/elektra-gcc-configure-xdg/src/libs/elektra/kdb.c:306
        Reason: Mounting global plugins failed
        Mountpoint: system/elektra
        Configfile: kdbOpen(): mountGlobals
STDOUT: 
=== FAILED stdout doesn't match expected pattern TEST
WARNINGS:  1, 64, 139,
ERRORS: 
DIFF: 70c70
< system/elektra/modules/dump/exports/getpR�

---
> system/elektra/modules/dump/exports/getp���
75c75
< system/elektra/modules/dump/exports/serialise�%�

---
> system/elektra/modules/dump/exports/serialise����
80c80
< system/elektra/modules/dump/exports/set`=�

---
> system/elektra/modules/dump/exports/set`���
```

**Comment by markus2330** [comment]
There are several severe problems with the shell recorder. As first step you should at least detect problems similar to tests/shell/run_all.sh. I updated a list of problems in the head of this issue.

**Comment by markus2330** [comment]
There is a severe issue that the shell recorder continues even if the backup (export in line 52) failed. I added it in the list above.

**Comment by markus2330** [comment]
@tom-wa Could you please check what was already done here?

**Comment by markus2330** [comment]
@tom-wa I added "testshell_* testcases do not execute anything, protocol file is empty.". `ctest -V -R testshell` should give more output, the protocol file should be cleaned up afterwards.

**Comment by tom-wa** [comment]
HEREDOC is supported by the MSR (see blockresolver/README.md for examples)
fail if backup failes also already implemented
 might remove keys    should also be fixed already

should the protocol file really be removed ? i read them quite often

**Comment by markus2330** [comment]
> HEREDOC is supported by the MSR

You can click in the list above to mark things done. (If they are really done!)

> should the protocol file really be removed ? i read them quite often

Even on success? We could add an option to keep the protocol on success but by default tools should be clean. (On error we should dump the protocol to stderr.)

**Comment by markus2330** [comment]
Is this for post-1.0? Then we usually close it and assign it to 2.0?
